wandb_version: 1

dataset:
  desc: null
  value:
    name: heofshfoseh
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686656091.349511
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.4
      8:
      - 5
