---

name: saint cicids2017
script: train
project: saint_nids
run_name: test_run 
log: False
eval_interval: 0

#dataset: cicids2017

defaults:
    - dataset: cicids2017
    - model: saint
    - hyperparameters: standard_hps
    - training_probe: linear
    - eval_probe: triplet
    - _self_
